'use client';

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto bg-white rounded-lg shadow-sm p-8">
        <h1 className="text-4xl font-bold text-gray-900 mb-8">Privacy Policy</h1>
        
        <p className="text-sm text-gray-500 mb-8">Last Updated: November 18, 2025</p>

        <div className="space-y-8 text-gray-700">
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">1. Introduction</h2>
            <p>
              Welcome to PostReady. We are committed to protecting your privacy and being transparent about how we collect, use, and store your data. This Privacy Policy explains our practices regarding data collection when you use our services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">2. Information We Collect</h2>
            
            <h3 className="text-xl font-semibold text-gray-800 mb-3 mt-4">2.1 Account Information</h3>
            <p className="mb-4">
              When you create an account, we collect:
            </p>
            <ul className="list-disc pl-6 space-y-2 mb-4">
              <li>Email address</li>
              <li>Account credentials (encrypted)</li>
              <li>Profile information you provide</li>
              <li>Subscription and payment information (processed securely through Stripe)</li>
            </ul>

            <h3 className="text-xl font-semibold text-gray-800 mb-3 mt-4">2.2 Social Media Page Analysis Data</h3>
            <p className="mb-4">
              When you use our Social Media Page Analyzer tool, we collect and store:
            </p>
            <ul className="list-disc pl-6 space-y-2 mb-4">
              <li><strong>Screenshots:</strong> Images you upload for analysis</li>
              <li><strong>Extracted Information:</strong> Data automatically extracted from screenshots including:
                <ul className="list-circle pl-6 mt-2 space-y-1">
                  <li>Usernames and handles</li>
                  <li>Display names</li>
                  <li>Follower counts</li>
                  <li>Post counts</li>
                  <li>Bio links</li>
                  <li>Social media profile URLs</li>
                </ul>
              </li>
              <li><strong>AI Analysis Results:</strong> The insights and recommendations generated by our AI</li>
              <li><strong>Timestamp:</strong> When the analysis was performed</li>
            </ul>

            <h3 className="text-xl font-semibold text-gray-800 mb-3 mt-4">2.3 Usage Data</h3>
            <p className="mb-4">
              We automatically collect:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Device information and browser type</li>
              <li>IP address and location data</li>
              <li>Pages visited and features used</li>
              <li>Session duration and interaction patterns</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">3. How We Use Your Information</h2>
            <p className="mb-4">We use collected data for:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Service Delivery:</strong> To provide and improve our AI-powered tools and features</li>
              <li><strong>Product Improvement:</strong> To analyze usage patterns and enhance our services</li>
              <li><strong>Quality Assurance:</strong> To train and improve our AI models</li>
              <li><strong>Customer Support:</strong> To respond to your inquiries and provide assistance</li>
              <li><strong>Security:</strong> To detect and prevent fraud, abuse, and security issues</li>
              <li><strong>Legal Compliance:</strong> To comply with legal obligations and enforce our terms</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">4. Data Storage and Security</h2>
            <p className="mb-4">
              We take data security seriously:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>All data is encrypted in transit (HTTPS) and at rest</li>
              <li>Screenshots are stored in private, access-controlled storage buckets</li>
              <li>Database access is restricted to authorized personnel only</li>
              <li>We use industry-standard security practices and regular security audits</li>
              <li>Payment information is processed securely through Stripe (PCI-DSS compliant)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">5. Data Retention</h2>
            <p className="mb-4">
              We retain your data as follows:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Account Data:</strong> Retained while your account is active and for a reasonable period after deletion</li>
              <li><strong>Analysis Data:</strong> Screenshots and extracted information are retained to improve our services</li>
              <li><strong>Usage Data:</strong> Aggregated and anonymized for analytics purposes</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">6. Your Rights</h2>
            <p className="mb-4">You have the right to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Access:</strong> Request a copy of your personal data</li>
              <li><strong>Correction:</strong> Update or correct inaccurate information</li>
              <li><strong>Deletion:</strong> Request deletion of your data (subject to legal requirements)</li>
              <li><strong>Opt-Out:</strong> Unsubscribe from marketing communications</li>
              <li><strong>Data Portability:</strong> Receive your data in a machine-readable format</li>
            </ul>
            <p className="mt-4">
              To exercise these rights, please contact us at: <a href="mailto:privacy@postready.com" className="text-blue-600 hover:underline">privacy@postready.com</a>
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">7. Third-Party Services</h2>
            <p className="mb-4">We use the following third-party services:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Stripe:</strong> Payment processing</li>
              <li><strong>OpenAI:</strong> AI analysis and content generation</li>
              <li><strong>Supabase:</strong> Database and storage infrastructure</li>
            </ul>
            <p className="mt-4">
              These services have their own privacy policies and we recommend reviewing them.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">8. Children's Privacy</h2>
            <p>
              Our services are not intended for users under 13 years of age. We do not knowingly collect personal information from children under 13.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">9. Changes to This Policy</h2>
            <p>
              We may update this Privacy Policy from time to time. We will notify you of significant changes by posting the new policy on this page and updating the "Last Updated" date.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">10. Contact Us</h2>
            <p className="mb-4">
              If you have questions about this Privacy Policy or our data practices, please contact us:
            </p>
            <ul className="space-y-2">
              <li><strong>Email:</strong> <a href="mailto:privacy@postready.com" className="text-blue-600 hover:underline">privacy@postready.com</a></li>
              <li><strong>Support:</strong> <a href="mailto:support@postready.com" className="text-blue-600 hover:underline">support@postready.com</a></li>
            </ul>
          </section>

          <section className="border-t pt-8 mt-8">
            <p className="text-sm text-gray-500">
              By using PostReady, you acknowledge that you have read and understood this Privacy Policy and agree to its terms.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
